# Generated by Django 6.0.4 on 2026-04-13 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Вопрос')),
                ('variant_1', models.CharField(verbose_name='Вариант ответа №1')),
                ('variant_2', models.CharField(verbose_name='Вариант ответа №2')),
                ('variant_3', models.CharField(verbose_name='Вариант ответа №3')),
                ('variant_4', models.CharField(verbose_name='Вариант ответа №4')),
                ('answer', models.CharField(verbose_name='Правильный ответ')),
            ],
            options={
                'verbose_name': 'Вопрос для 1 раунда',
                'verbose_name_plural': 'Вопросы для 1 раунда',
            },
        ),
        migrations.CreateModel(
            name='GameRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(default='Киноман', max_length=100)),
                ('correct_answers', models.IntegerField()),
                ('total_questions', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-correct_answers', '-date'],
            },
        ),
    ]
