# Generated by Django 6.0.1 on 2026-02-02 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qustion', models.TextField(verbose_name='Вопрос')),
                ('variant_1', models.CharField(verbose_name='Вариант ответа №1')),
                ('variant_2', models.CharField(verbose_name='Вариант ответа №2')),
                ('variant_3', models.CharField(verbose_name='Вариант ответа №3')),
                ('variant_4', models.CharField(verbose_name='Вариант ответа №4')),
                ('answer', models.CharField(verbose_name='Правильный ответ')),
            ],
        ),
    ]
