# Generated by Django 6.0.1 on 2026-02-21 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roundone', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': 'Вопрос для 1 раунда', 'verbose_name_plural': 'Вопросы для 1 раунда'},
        ),
        migrations.RenameField(
            model_name='articles',
            old_name='qustion',
            new_name='question',
        ),
    ]
