# Generated by Django 6.0.1 on 2026-02-21 23:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roundone', '0002_alter_articles_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(default='Киноман', max_length=100)),
                ('correct_answers', models.IntegerField()),
                ('total_questions', models.IntegerField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-correct_answers', '-date'],
            },
        ),
    ]
