# Generated by Django 6.0.4 on 2026-04-13 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roundone', '0003_gamerecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamerecord',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
